MODEL_PHOBERT_BASE = "phobert_base"
MODEL_PHOBERT_LARGE = "phobert_large"
MODEL_BILSTM = "bilstm"
MODEL_BILSTM_CRF = "bilstm_crf"
MODEL_PHOBERT_BASE_BILSTM = "phobert_base_bilstm"
MODEL_PHOBERT_BASE_BILSTM_CRF = "phobert_base_bilstm_crf"
MODEL_PHOBERT_LARGE_BILSTM = "phobert_large_bilstm"
MODEL_PHOBERT_LARGE_BILSTM_CRF = "phobert_large_bilstm_crf"

RESOURCE_PHOBERT_BASE = "resources/phobert_base"
RESOURCE_PHOBERT_LARGE = "resources/phobert_large"
RESOURCE_BILSTM = "resources/bilstm.h5"
RESOURCE_BILSTM_CRF = "resources/bilstm_crf/bilstm_crf"
RESOURCE_PHOBERT_BASE_BILSTM = "resources/phobert_base_bilstm/phobert_base_bilstm"
RESOURCE_PHOBERT_BASE_BILSTM_CRF = "resources/phobert_base_bilstm_crf/phobert_base_bilstm_crf"
RESOURCE_PHOBERT_LARGE_BILSTM = "resources/phobert_large_bilstm/phobert_large_bilstm"
RESOURCE_PHOBERT_LARGE_BILSTM_CRF = "resources/phobert_large_bilstm_crf/phobert_large_bilstm_crf"

LANGUAGE_EN = "en"
LANGUAGE_VI = "vi"